# Generated by Django 4.2.2 on 2023-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_drink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=200)),
                ("sex", models.CharField(max_length=100)),
            ],
        ),
    ]
