# Generated by Django 4.2.2 on 2023-07-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0003_employees"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrinkFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("feedback", models.CharField(max_length=2000)),
            ],
        ),
    ]
