# Generated by Django 4.2.2 on 2023-07-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0005_users"),
    ]

    operations = [
        migrations.DeleteModel(name="Users",),
    ]
